version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    healthcheck:
      test:
        ["CMD-SHELL", 'mongosh --eval ''db.adminCommand("ping")'' || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sync-api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_data:

networks:
  backend:
